# Generated by Django 3.2.23 on 2024-01-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240102_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebookUrl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tiktokUrl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitterUrl',
        ),
        migrations.AddField(
            model_name='profile',
            name='content_social',
            field=models.TextField(blank=True),
        ),
    ]
