# Generated by Django 3.2.23 on 2024-01-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20240103_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipient',
        ),
    ]
